$(function(){
    //attiva-disattiva gli input del prezzo
    $('#cPrezzo').on('change',function(){
        if($(this).is(':checked')){
            $('#minP').prop('disabled', false);
            $('#maxP').prop('disabled', false);
        }
        else{
            $('#minP').prop('disabled',true);
            $('#maxP').prop('disabled',true);
        }
    });
    $('#dataI').on('change',function(){
        if($(this).is(':checked')){
            $('#oDate').prop('disabled',false);
        }
        else{
            $('#oDate').prop('disabled',true);
        }
    });
    $('#dataF').on('change',function(){
        if($(this).is(':checked')){
            $('#rDate').prop('disabled',false);
        }
        else{
            $('#rDate').prop('disabled',true);
        }
    });
    $('#cStato').on('change',function(){
        if($(this).is(':checked')){
            $('#stato').prop('disabled',false);
        }
        else{
            $('#stato').prop('disabled',true);
        }
    });
    $('#cCitta').on('change',function(){
        if($(this).is(':checked')){
            $('#citta').prop('disabled',false);
        }
        else{
            $('#citta').prop('disabled',true);
        }
    });
});